"""Generate the provenance map: every artefact, what produced it, and what it was produced from.

Written rather than hand-maintained, because a hand-maintained map is a document that agrees with
the pipeline on the day it is written. The edges come from the same declaration
tools/check_freshness.py uses, so the map and the staleness check cannot disagree: if an edge is
missing here it is missing there too, and the freshness check will not be guarding it.

Each edge records the script that produces the output and the inputs it consumes. Each node records
whether the artefact exists, its size, and when it was last written, so the map is a statement about
this repository now rather than about an intended design.

The chain runs raw data -> processed tables -> models -> validation -> statistics -> figures ->
manuscript, and the manuscript layer is included because a number in a paper is an artefact with a
producer like any other.

Outputs: repro/PROVENANCE.md, repro/provenance.json

Run:  python tools/build_provenance.py
"""
from __future__ import annotations

import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from check_freshness import GRAPH, newest  # noqa: E402

OUT = ROOT / "repro"

# Which layer each artefact belongs to, matched on a path prefix. Ordered, first match wins.
LAYERS = [
    ("data/endpoints", "1. processed data"),
    ("data/", "1. processed data"),
    ("models_rf/holdout", "3. validation inputs"),
    ("models_rf/", "2. models"),
    ("results/tables/rf_cv", "4. statistics"),
    ("results/tables/MODEL_INVENTORY", "4. statistics"),
    ("results/tables/", "3. validation"),
    ("reviewer_package/", "5. reviewer package"),
    ("manuscript/figures", "6. figures"),
    ("manuscript/tables", "7. tables"),
    ("manuscript/", "8. manuscript"),
    ("models_manifest.json", "9. deposit"),
]

# Sources upstream of everything, recorded because the chain has to start somewhere real.
RAW = [
    ("ChEMBL", "data/_chembl_cache/", "src/brainsafe/data/fetch_endpoints.py",
     "measured activities and censored bounds, cached as retrieved"),
    ("BindingDB", "data/_bindingdb_cache/", "src/brainsafe/data/fetch_bindingdb.py",
     "measured binding affinities"),
    ("B3DB", "data/endpoints/BBB.csv", "src/brainsafe/data/fetch_endpoints.py",
     "blood-brain barrier labels, plus FDA-curated approved drugs"),
    ("Therapeutics Data Commons / MoleculeNet", "data/adme/", "src/brainsafe/adme/fetch_adme.py",
     "measured ADME and exposure endpoints"),
]


def layer_of(path: str) -> str:
    for prefix, name in LAYERS:
        if path.startswith(prefix):
            return name
    return "other"


def node(path: str) -> dict:
    ts, f = newest(path)
    p = ROOT / path
    if "*" in path:
        hits = sorted(ROOT.glob(path))
        size = sum(q.stat().st_size for q in hits)
        exists, n = bool(hits), len(hits)
    elif p.is_dir():
        hits = [q for q in p.rglob("*") if q.is_file()]
        size = sum(q.stat().st_size for q in hits)
        exists, n = bool(hits), len(hits)
    else:
        exists = p.exists()
        size = p.stat().st_size if exists else 0
        n = 1 if exists else 0
    return {"path": path, "layer": layer_of(path), "exists": exists, "n_files": n,
            "bytes": size,
            "last_written": dt.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M") if ts else None}


def human(b: int) -> str:
    for unit in ("B", "kB", "MB", "GB"):
        if b < 1024 or unit == "GB":
            return f"{b:.0f} {unit}" if unit == "B" else f"{b:.1f} {unit}"
        b /= 1024
    return f"{b:.1f} GB"


def main() -> None:
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                            capture_output=True, text=True).stdout.strip()
    today = dt.date.today().isoformat()

    edges, nodes = [], {}
    for out, ins, cmd in GRAPH:
        edges.append({"output": out, "inputs": list(ins), "script": cmd,
                      "layer": layer_of(out)})
        for path in [out, *ins]:
            if path not in nodes:
                nodes[path] = node(path)

    doc = {"generated": today, "commit": commit, "raw_sources": [
        {"source": s, "lands_in": p, "script": c, "contents": d} for s, p, c, d in RAW],
        "edges": edges, "nodes": nodes}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "provenance.json").write_text(json.dumps(doc, indent=2), encoding="utf-8")

    # ---- the readable version -------------------------------------------------------------
    L = [f"# Provenance map, {today}", "",
         f"Commit `{commit}`. Generated by `tools/build_provenance.py` from the same dependency",
         "declaration that `tools/check_freshness.py` enforces, so the map cannot drift from the",
         "check: an edge missing here is unguarded there.", "",
         "Every edge names the script that produces the output and the inputs it consumes. Every",
         "node records whether the artefact exists and when it was last written, so this describes",
         "the repository as it is rather than as it was designed.", "",
         "## Raw sources", "",
         "| source | lands in | retrieved by | contents |", "|---|---|---|---|"]
    for s, p, c, d in RAW:
        L.append(f"| {s} | `{p}` | `{c}` | {d} |")

    L += ["", "## The chain", "",
          "Read each row as: **inputs** produce **output** by running **script**.", ""]
    for layer in sorted({e["layer"] for e in edges}):
        L += [f"### {layer}", "", "| output | produced from | script | last written |",
              "|---|---|---|---|"]
        for e in [x for x in edges if x["layer"] == layer]:
            n = nodes[e["output"]]
            stamp = n["last_written"] or "**MISSING**"
            ins = "<br>".join(f"`{i}`" for i in e["inputs"])
            cmd = e["script"].replace(" && ", "<br>")
            L.append(f"| `{e['output']}` | {ins} | `{cmd}` | {stamp} |")
        L.append("")

    missing = [p for p, n in nodes.items() if not n["exists"]]
    total = sum(n["bytes"] for n in nodes.values())
    L += ["## Inventory", "",
          f"- {len(nodes)} artefacts, {len(edges)} edges, {human(total)} on disk",
          f"- missing: {', '.join(f'`{m}`' for m in missing) if missing else 'none'}",
          "",
          "## Regenerating",
          "",
          "```bash",
          "make reproduce        # metrics, figures and the manuscript, in dependency order",
          "make check            # freshness, tests and the reproduction ledger",
          "```",
          "",
          "`make reproduce` does not retrain. Training is hours and is a deliberate act; see",
          "`REPRODUCE.md` for the full chain including `make train`."]
    (OUT / "PROVENANCE.md").write_text("\n".join(L), encoding="utf-8")

    print(f"{len(nodes)} artefacts, {len(edges)} edges, {human(total)}")
    print(f"missing: {missing or 'none'}")
    print("wrote repro/PROVENANCE.md and repro/provenance.json")


if __name__ == "__main__":
    main()
